apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: occurrence-driven-demo-apis
  description: A collection of all Backstage occurrence-driven-demo APIs
spec:
  targets:
    - ./apis/order-command-side-api.yaml
    - ./apis/order-query-side-api.yaml
    - ./apis/payment-command-side-api.yaml
    - ./apis/payment-query-side-api.yaml
    - ./apis/shipment-command-side-api.yaml
    - ./apis/shipment-query-side-api.yaml
