version: "3"
services:
  order-command:
    image: 'dhowlathbasha/oddemo-order-command-side:${APP_TAG:-latest}'
    ports:
      - '8081:8081'
    depends_on:
      - kafka
    profiles:
      - all
      - order
      - command
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  order-handler:
    image: 'dhowlathbasha/oddemo-order-event-handler:${APP_TAG:-latest}'
    ports:
      - '8082:8082'
    depends_on:
      - kafka
    profiles:
      - all
      - order
      - handler
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  order-query:
    image: 'dhowlathbasha/oddemo-order-query-side:${APP_TAG:-latest}'
    ports:
      - '8083:8083'
    depends_on:
      - kafka
    profiles:
      - all
      - order
      - query
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  payment-command:
    image: 'dhowlathbasha/oddemo-payment-command-side:${APP_TAG:-latest}'
    ports:
      - '9081:9081'
    depends_on:
      - kafka
    profiles:
      - all
      - payment
      - command
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  payment-handler:
    image: 'dhowlathbasha/oddemo-payment-event-handler:${APP_TAG:-latest}'
    ports:
      - '9082:9082'
    depends_on:
      - kafka
    profiles:
      - all
      - payment
      - handler
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  payment-query:
    image: 'dhowlathbasha/oddemo-payment-query-side:${APP_TAG:-latest}'
    ports:
      - '9083:9083'
    depends_on:
      - kafka
    profiles:
      - all
      - payment
      - query
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  shipment-command:
    image: 'dhowlathbasha/oddemo-shipment-command-side:${APP_TAG:-latest}'
    ports:
      - '10081:10081'
    depends_on:
      - kafka
    profiles:
      - all
      - shipment
      - command
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  shipment-handler:
    image: 'dhowlathbasha/oddemo-shipment-event-handler:${APP_TAG:-latest}'
    ports:
      - '10082:10082'
    depends_on:
      - kafka
    profiles:
      - all
      - shipment
      - handler
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker
  shipment-query:
    image: 'dhowlathbasha/oddemo-shipment-query-side:${APP_TAG:-latest}'
    ports:
      - '10083:10083'
    depends_on:
      - kafka
    profiles:
      - all
      - shipment
      - query
    networks:
      - oddemo
    env_file:
      - ./config/.env.docker

networks:
  oddemo: