global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'cluster-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'order-command'
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'order-handler'
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'order-query'
      - targets: [ 'host.docker.internal:9081' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'payment-command'
      - targets: [ 'host.docker.internal:9082' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'payment-handler'
      - targets: [ 'host.docker.internal:9083' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'payment-query'
      - targets: [ 'host.docker.internal:10081' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'shipment-command'
      - targets: [ 'host.docker.internal:10082' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'shipment-handler'
      - targets: [ 'host.docker.internal:10083' ]
        labels:
          namespace: 'occurrence-driven'
          app: 'shipment-query'
